### ISSUE TITLE
Error "Eccentricity is out of bounds"

### ISSUE THREAD

**Issue by JDragonB** [1manprojects/one_Sgp4#28]
Hi, I have tracked 9684 satellites and I got this error on 6 of them :
DateTime : 09/02/2023 14:29:03 (France)
Satellites : LEMUR 2 KOBYSZCZE, AEROCUBE 14A, FLOCK 3P 61, NACHOS-1, AEROCUBE 15A, DANTESAT
TLE-Data : JSON from Space-Track (07/02/2023 16h21 France)
Function : [One_Sgp4.SatFunctions]::getSatPositionAtTime
Error : 
```
Exception lors de l'appel de « getSatPositionAtTime » avec « 3 » argument(s) : « LEMUR 2 KOBYSZCZE -Eccentricity is out of bounds
Nom du paramètre : Sgp4Calculation »
Au caractère D:\Samuel\Bureau\C2 FACTORY\Scripts\Space Vision 2\Space Vision 2.ps1:887 : 9
+         $DataECI = [One_Sgp4.SatFunctions]::getSatPositionAtTime($Par ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
```

![image](https://user-images.githubusercontent.com/68791091/217853021-43a9c819-92a7-4b85-9894-ec8ddf63f28f.png)

- Device: Desktop
 - OS: Windows 11 (the last build)
 - Language Powershell 5.1 and .NET

**Comment by 1manprojects** [comment]
Please check the satellites that throw this error if they are still in orbit. For example the **LEMUR 2 KOBYSZCZE** is no longer in orbit and as decayed on the 2023-02-03.

If the TLE - Data is outdated or the Satellite is no longer in orbit the orbital calculations will result in a -Eccentricity out of bounds error. 
This is expected behavior. This exception will be thrown for multiple reasons like the input data is outdated, wrong or the orbit has decayed. The library cannot determine the exact reason thus an exception is thrown. 

This was already discussed in #18

**Comment by JDragonB** [comment]
Rhaaa... thanks.

I had check that but sometime before...
![image](https://user-images.githubusercontent.com/68791091/217861628-377bbc91-4602-41c3-80f6-b6c423b1d970.png)

Finally everything is working too well!
